# Generated by Django 5.2.5 on 2025-08-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(upload_to='galeria/img/'),
        ),
    ]
