# Generated by Django 5.2.5 on 2025-08-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0003_alter_foto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(upload_to='galeria/img/'),
        ),
    ]
